from . import test_service_tree
from . import test_auto_add_service
from . import test_named_domain_rename
from . import test_weekend_deadline_rule
from . import test_auto_progress
from . import test_auto_done_children
from . import test_deferred_children
from . import test_supply_time
from . import test_transition_email_template
from . import test_project_deadline
from . import test_wizard_selection_sync
from . import test_reset_workflow
from . import test_service_template_placement
from . import test_subject_cascade
from . import test_workflow_icons
from . import test_bot_one_live_slot
from . import test_transition_buttons_bot_hide
from . import test_bot_execute
from . import test_service_hooks
from . import test_work_contract
from . import test_team_channel_copy
from . import test_review_email_bounce
